'use strict';

const mongoose = require('mongoose');

// Explicit, informed, versioned consent for processing special-category (GDPR Art.9)
// health/biometric data (audit H-9). The OS/OAuth read grants alone are NOT lawful Art.9
// consent — this collection is the record of it.
//
// APPEND-ONLY: a withdrawal is a NEW row (status: 'withdrawn'), never an in-place mutation of
// a granted row. The full grant→withdraw→re-grant history is therefore preserved, and the
// user's CURRENT state is the LATEST row (see `latestFor`) — never "any granted row", which
// would wrongly still read as consented after a withdrawal.
const consentRecordSchema = new mongoose.Schema({
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
  // Start with a single purpose; the enum makes adding future purposes an explicit, reviewed change.
  purpose: {
    type: String,
    enum: ['health_biometric_processing'],
    required: true,
  },
  // Bumped in services/privacy/consent.js (CURRENT_CONSENT_VERSION) whenever the consent text /
  // data categories materially change — a row at an older version reads as stale (re-prompt).
  consentVersion: { type: Number, required: true },
  // The special-category data categories the user consented to — the provider-specific union across
  // wearable lanes: Health Connect (heart_rate, hrv, sleep, resting_heart_rate, historical) plus the
  // Garmin server-to-server lane (spo2, respiratory_rate, body_battery). mobile consentApi.ts
  // CONSENT_DATA_CATEGORIES is the authoritative list; kept as the client sent it so the record
  // reflects exactly what was shown.
  dataCategories: { type: [String], default: [] },
  status: {
    type: String,
    enum: ['granted', 'withdrawn'],
    required: true,
  },
  grantedAt:   { type: Date },
  withdrawnAt: { type: Date },
  // Provenance for the Art.7 record of consent — where/how it was captured. Optional.
  appVersion: { type: String },
  locale:     { type: String },
}, {
  timestamps: true, // createdAt orders the append-only history so "latest" is deterministic
});

consentRecordSchema.index({ userId: 1, purpose: 1, consentVersion: 1 });

// How many of the newest rows the read scans to assemble the same-millisecond tie group. It must
// cover the WHOLE tied millisecond for the fail-closed rule below to mean anything: ordering the
// group by _id can put two grants ahead of a withdrawal that shares their millisecond, so a
// 2-row window would silently read as consented (measured — pinned by the "not among the newest
// _ids" test). Consent rows are user-initiated toggles, so a millisecond realistically holds one
// or two; 16 is far above any real burst, and it costs nothing extra — the query matches on
// (userId, purpose) either way, so the limit only caps how many tiny docs are materialised.
// A window that comes back FULL is treated as possibly truncated rather than complete.
const TIE_SCAN_LIMIT = 16;
consentRecordSchema.statics.TIE_SCAN_LIMIT = TIE_SCAN_LIMIT;

// True iff both ObjectIds were generated by the SAME process. An ObjectId is
// [4-byte seconds | 5-byte per-process random | 3-byte per-process counter] (hex chars 8..18 are
// that middle field), so an equal middle field means one generator — and therefore a counter that
// genuinely encodes generation order. Anything that is not a real ObjectId reads as a different
// writer, which is the fail-closed direction.
const sameWriter = (a, b) => {
  if (typeof a?.toHexString !== 'function' || typeof b?.toHexString !== 'function') return false;
  return a.toHexString().slice(8, 18) === b.toHexString().slice(8, 18);
};

// The consent-status read path: newest row for a user+purpose. `createdAt` is millisecond-
// resolution, so two writes can tie — and the right answer depends on WHO wrote them
// (resilience-audit finding): ObjectIds are monotonic only WITHIN a single process, because the
// counter is per-process, so across replicas (Railway can run more than one) an _id tie-break
// alone is not reliable. This read therefore splits the two cases instead of guessing at both:
// a tie among rows from ONE process is resolved by _id, since the counter is a record of the
// insertion order and discarding it made a re-grant read as a withdrawal (W4-D29); a tie spanning
// writers is genuinely unordered, so it fails CLOSED and prefers 'withdrawn' — a same-millisecond
// race must never read as consented when a withdrawal also landed.
consentRecordSchema.statics.latestFor = async function (userId, purpose) {
  const rows = await this.find({ userId, purpose })
    .sort({ createdAt: -1, _id: -1 })
    .limit(TIE_SCAN_LIMIT)
    .exec();
  if (!rows.length) return null;

  const newest = rows[0];
  const newestMs = newest.createdAt.getTime();
  const tied = rows.filter((r) => r.createdAt.getTime() === newestMs);
  if (tied.length === 1) return newest;

  if (tied.length === TIE_SCAN_LIMIT) {
    // The window is full, so it proves neither "one writer" nor "no withdrawal" — ask directly.
    const withdrawn = await this.findOne({ userId, purpose, createdAt: newest.createdAt, status: 'withdrawn' }).exec();
    return withdrawn || newest;
  }
  // One writer: the sort already put that process's last-generated row first.
  if (tied.every((r) => sameWriter(r._id, newest._id))) return newest;
  return tied.find((r) => r.status === 'withdrawn') || newest;
};

module.exports = mongoose.model('ConsentRecord', consentRecordSchema);
